import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Check, CircuitBoard, FileCheck2, Headphones, Home, MessageCircle, Phone, ShieldCheck, Sparkles } from "lucide-react";
import { ProductCard } from "@/components/product-card";
import { getCategories,getProducts,getSiteSettings } from "@/lib/queries";
export default async function HomePage(){const[products,categories,settings]=await Promise.all([getProducts(),getCategories(),getSiteSettings()]);const featured=products.filter(p=>p.featured).slice(0,3);const heroProduct=featured.find(product=>product.images[0]?.url)||products.find(product=>product.images[0]?.url);const heroImage=settings.heroImageUrl||heroProduct?.images[0]?.url;const trustIcons=[ShieldCheck,Headphones,FileCheck2];return <>
<section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="mini"><Sparkles size={15}/> {settings.heroKicker}</span><h1>{settings.heroTitle} <span>{settings.heroHighlight}</span></h1><p>{settings.heroDescription}</p><div className="hero-actions"><Link href="/san-pham" className="button button-primary">{settings.heroPrimaryLabel} <ArrowRight size={18}/></Link>{(settings.hotline||settings.zalo)&&<a href="#lien-he" className="button button-secondary">{settings.heroSecondaryLabel}</a>}</div><div className="hero-trust">{settings.heroTrustItems.map((item,index)=>{const Icon=trustIcons[index]||ShieldCheck;return <div key={`${item}-${index}`}><Icon size={21}/> {item}</div>})}</div></div><div className="hero-visual">{heroImage?<div className="hero-photo"><Image src={heroImage} alt={settings.heroImageUrl?"Sản phẩm S HOUSE":"Sản phẩm "+(heroProduct?.name||"S HOUSE")} fill sizes="(max-width: 900px) 100vw, 50vw" loading="eager"/></div>:<div className="hero-empty"><CircuitBoard/><strong>Ảnh sản phẩm đang được cập nhật</strong></div>}<div className="hero-tag"><strong>{settings.heroCardTitle}</strong><span>{settings.heroCardDescription}</span></div></div></div></section>
<section className="section section-soft"><div className="container"><div className="section-heading category-section-heading"><span className="section-kicker">Danh mục sản phẩm</span><h2>Giải pháp phù hợp <span>với từng nhu cầu</span></h2><p>Khám phá các nhóm sản phẩm đang được S HOUSE cung cấp.</p></div>{categories.length?<div className="category-grid">{categories.slice(0,3).map(cat=><Link href={`/san-pham?danh-muc=${cat.slug}`} className="category-card" key={cat.id}><span className={`category-card-media${cat.imageUrl?" has-image":""}`}>{cat.imageUrl?<Image src={cat.imageUrl} alt={`Ảnh đại diện ${cat.name}`} fill sizes="(max-width: 600px) calc(100vw - 48px), (max-width: 900px) 45vw, 30vw"/>:<span className="category-card-placeholder"><strong>S HOUSE</strong><small>Ảnh danh mục đang cập nhật</small></span>}</span><span className="category-card-content"><span className="category-card-title"><h3>{cat.name}</h3><span className="arrow"><ArrowRight size={18}/></span></span><p>{cat.description||"Thông tin danh mục đang được cập nhật."}</p></span></Link>)}</div>:<div className="empty-state"><CircuitBoard/><h3>Danh mục đang được cập nhật</h3><p>Vui lòng quay lại sau.</p></div>}</div></section>
<section className="section"><div className="container"><div className="section-heading"><div><span className="section-kicker">Được quan tâm</span><h2>Sản phẩm nổi bật</h2></div><Link href="/san-pham" className="text-link">Xem tất cả <ArrowRight size={18}/></Link></div>{featured.length?<div className="product-grid">{featured.map(product=><ProductCard key={product.id} product={product}/>)}</div>:<div className="empty-state"><CircuitBoard/><h3>Sản phẩm đang được cập nhật</h3><p>Quản trị viên chưa xuất bản sản phẩm nổi bật.</p></div>}</div></section>
<section className="section section-soft" id="gioi-thieu"><div className="container about-grid"><div className={`about-visual${settings.aboutImageUrl?" has-image":""}`}>{settings.aboutImageUrl?<Image src={settings.aboutImageUrl} alt="Không gian giới thiệu S HOUSE" fill sizes="(max-width: 900px) 100vw, 42vw"/>:<><div className="about-pattern"/><div className="about-house"><Home/></div><div className="about-card"><strong>S HOUSE</strong><span>{settings.aboutTitle}</span></div></>}</div><div className="content-heading"><span className="section-kicker">{settings.aboutKicker}</span><h2>{settings.aboutTitle}</h2><p>{settings.about||"Thông tin giới thiệu S HOUSE đang được cập nhật."}</p><div className="check-list">{settings.aboutFeatures.map((feature,index)=><div key={`${feature.title}-${index}`}><i><Check/></i><p><strong>{feature.title}</strong><span>{feature.description}</span></p></div>)}</div><Link href="/san-pham" className="button button-primary">{settings.aboutCtaLabel} <ArrowRight size={18}/></Link></div></div></section>
{(settings.hotline||settings.zalo)&&<section className="section contact-section" id="lien-he"><div className="container"><div className="contact-panel"><div className="contact-copy"><span className="contact-kicker"><Headphones/> Tư vấn trực tiếp</span><h2>Bạn cần tư vấn sản phẩm?</h2><p>Liên hệ S HOUSE để nhận thông tin phù hợp với nhu cầu thực tế.</p></div><div className="contact-actions">{settings.hotline&&<a href={`tel:${settings.hotline.replace(/\s/g,"")}`} className="button contact-call"><Phone/> <span><small>Gọi hotline</small>{settings.hotline}</span></a>}{settings.zalo&&<a href={`https://zalo.me/${settings.zalo.replace(/\s/g,"")}`} className="button contact-zalo"><MessageCircle/> <span><small>Trò chuyện qua</small>Zalo</span><ArrowRight/></a>}</div></div></div></section>}
</>}
