import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AlignLeft, ArrowLeft, Download, FileText, ListChecks, MessageCircle, Phone } from "lucide-react";
import { ProductGallery } from "@/components/product-gallery";
import { RichDescription } from "@/components/rich-description";
import { formatPrice } from "@/lib/models";
import { getProductBySlug, getSiteSettings } from "@/lib/queries";

type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const{slug}=await params;const product=await getProductBySlug(slug);return product?{title:product.name,description:product.shortDescription,alternates:{canonical:`/san-pham/${product.slug}`},openGraph:{type:"website",locale:"vi_VN",title:product.name,description:product.shortDescription,url:`/san-pham/${product.slug}`,images:product.images[0]?.url?[{url:product.images[0].url,alt:product.images[0].altText||product.name}]:undefined},twitter:{card:"summary_large_image",title:product.name,description:product.shortDescription,images:product.images[0]?.url?[product.images[0].url]:undefined}}:{title:"Không tìm thấy sản phẩm"}}
export default async function ProductDetail({params}:Props){const{slug}=await params;const[product,settings]=await Promise.all([getProductBySlug(slug),getSiteSettings()]);if(!product)notFound();const phone=settings.hotline.replace(/\s/g,"");const zalo=settings.zalo.replace(/\s/g,"");return <><section className="product-detail"><div className="container"><Link href="/san-pham" className="back-link"><ArrowLeft size={17}/> Quay lại danh sách</Link><div className="detail-grid"><ProductGallery product={product}/><div className="detail-info"><span className="eyebrow">{product.categoryName}</span><h1>{product.name}</h1><p className="product-code">Mã sản phẩm: <strong>{product.code}</strong></p>{product.shortDescription&&<p className="lead">{product.shortDescription}</p>}<div className="detail-price"><span>Giá</span><strong>{formatPrice(product.price)}</strong></div>{(phone||zalo)&&<div className="detail-actions">{phone&&<a className="button button-primary" href={`tel:${phone}`}><Phone size={18}/> Gọi tư vấn</a>}{zalo&&<a className="button button-secondary" href={`https://zalo.me/${zalo}`} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Nhắn Zalo</a>}</div>}</div></div></div></section><section className="section section-soft"><div className="container detail-content"><article className="detail-section-card description-card"><header className="detail-section-heading"><i><AlignLeft/></i><div><span className="section-kicker">Thông tin sản phẩm</span><h2>Mô tả chi tiết</h2></div></header><RichDescription content={product.description}/>{product.pdfPath&&<div className="pdf-card"><FileText/><div><strong>Tài liệu sản phẩm</strong><span>Định dạng PDF</span></div>{product.pdfUrl?<a href={product.pdfUrl} target="_blank" rel="noreferrer"><Download/> Tải PDF</a>:<span>Không thể tải file</span>}</div>}</article><aside className="detail-section-card specs-card"><header className="detail-section-heading"><i><ListChecks/></i><div><span className="section-kicker">Thông số</span><h2>Bảng thông số kỹ thuật</h2></div></header>{product.specs.length?<div className="spec-table">{product.specs.map(spec=><div key={spec.id||spec.name}><span>{spec.name}</span><strong>{spec.value}{spec.unit&&` ${spec.unit}`}</strong></div>)}</div>:<p className="empty-copy">Thông số đang được cập nhật.</p>}</aside></div></section></>}
