"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Eye,FileText,GripVertical,History,ImagePlus,Save,Star,Trash2,Upload } from "lucide-react";
import { type FormEvent,useEffect,useRef,useState,useTransition } from "react";
import { deleteProductImage,reorderProductImages,saveProduct,setCoverImage } from "@/app/admin/actions/products";
import { discardProductUploads,finalizeProductUploads,prepareProductUploads } from "@/app/admin/actions/product-uploads";
import { validateImage,validatePdf } from "@/app/admin/actions/file-validation";
import type { ActionState } from "@/app/admin/actions/types";
import type { Category,Product,ProductImage,ProductSpec } from "@/lib/models";
import { slugifyVietnamese } from "@/lib/slugify";
import { createClient } from "@/lib/supabase/client";
import { MarkdownEditor } from "./markdown-editor";
import { SpecificationEditor } from "./specification-editor";

type Preview={file:File;url:string;altText:string};
export function ProductEditorV2({product,categories}:{product?:Product;categories:Category[]}){
 const router=useRouter();
 const[state,setState]=useState<ActionState>({});const[pending,setPending]=useState(false);const[uploadStatus,setUploadStatus]=useState("");
 const[specs,setSpecs]=useState<ProductSpec[]>(product?.specs.length?product.specs.map(spec=>({...spec,value:spec.unit?`${spec.value} ${spec.unit}`.trim():spec.value,unit:""})):[{name:"",value:"",unit:""}]);
 const[previews,setPreviews]=useState<Preview[]>([]);const previewRef=useRef<Preview[]>([]);const fileRef=useRef<HTMLInputElement>(null);
 const[existingImages,setExistingImages]=useState<ProductImage[]>(product?.images??[]);const[dragId,setDragId]=useState<string>();
 const[name,setName]=useState(product?.name??"");const[slug,setSlug]=useState(product?.slug??"");const[slugManual,setSlugManual]=useState(Boolean(product));
 const[dirty,setDirty]=useState(false);const[imageError,setImageError]=useState("");const[imagePending,startImageTransition]=useTransition();
 useEffect(()=>()=>previewRef.current.forEach(item=>URL.revokeObjectURL(item.url)),[]);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
 useEffect(()=>{const guard=(event:MouseEvent)=>{const target=event.target as HTMLElement|null;const link=target?.closest("a[href]") as HTMLAnchorElement|null;if(!dirty||!link||link.target==="_blank")return;if(!confirm("Bạn có thay đổi chưa lưu. Vẫn rời khỏi trang?")){event.preventDefault();event.stopPropagation()}};document.addEventListener("click",guard,true);return()=>document.removeEventListener("click",guard,true)},[dirty]);
 const sync=(next:Preview[])=>{previewRef.current=next;setPreviews(next);const transfer=new DataTransfer();next.forEach(item=>transfer.items.add(item.file));if(fileRef.current)fileRef.current.files=transfer.files};
 const choose=(files:FileList|null)=>{if(!files)return;previews.forEach(item=>URL.revokeObjectURL(item.url));sync([...files].slice(0,8).map(file=>({file,url:URL.createObjectURL(file),altText:name})));setDirty(true)};
 function moveExisting(targetId:string){if(!product||!dragId||dragId===targetId)return;const from=existingImages.findIndex(item=>item.id===dragId);const to=existingImages.findIndex(item=>item.id===targetId);const next=[...existingImages];const[moved]=next.splice(from,1);next.splice(to,0,moved);setExistingImages(next);setDragId(undefined);startImageTransition(async()=>{try{await reorderProductImages(product.id,next.map(item=>item.id))}catch{setImageError("Không thể lưu thứ tự ảnh.")}})}
 function movePreview(from:number,to:number){if(from===to)return;const next=[...previews];const[moved]=next.splice(from,1);next.splice(to,0,moved);sync(next)}
 function removeImage(image:ProductImage){if(!confirm("Xóa ảnh này khỏi sản phẩm?"))return;startImageTransition(async()=>{try{await deleteProductImage(image.id);setExistingImages(items=>items.filter(item=>item.id!==image.id))}catch{setImageError("Không thể xóa ảnh.")}})}
 function coverImage(image:ProductImage){if(image.isCover)return;startImageTransition(async()=>{try{await setCoverImage(image.id);setExistingImages(items=>items.map(item=>({...item,isCover:item.id===image.id})))}catch{setImageError("Không thể chọn ảnh đại diện.")}})}
 async function handleSubmit(event:FormEvent<HTMLFormElement>){
  event.preventDefault();if(pending)return;setPending(true);setState({});setImageError("");setUploadStatus("Đang kiểm tra dữ liệu...");
  try{
   const formData=new FormData(event.currentTarget);const pdfValue=formData.get("pdf");const pdf=pdfValue instanceof File&&pdfValue.size>0?pdfValue:null;
   for(const preview of previews){const error=await validateImage(preview.file);if(error){setState({error});return}}
   if(pdf){const error=await validatePdf(pdf);if(error){setState({error});return}}
   formData.delete("images");formData.delete("newImageAlt");formData.delete("pdf");
   setUploadStatus("Đang lưu thông tin sản phẩm...");const saved=await saveProduct({},formData);
   if(saved.error||!saved.productId){setState({error:saved.error||"Không thể lưu sản phẩm."});return}
   if(!previews.length&&!pdf){setDirty(false);router.push(`/admin/san-pham/${saved.productId}?saved=1`);router.refresh();return}
   setUploadStatus("Đang chuẩn bị vùng tải file bảo mật...");
   const prepared=await prepareProductUploads(saved.productId,{images:previews.map(item=>({name:item.file.name,size:item.file.size,type:item.file.type})),pdf:pdf?{name:pdf.name,size:pdf.size,type:pdf.type}:null});
   if("error" in prepared){setState({error:prepared.error});return}
   const allPaths=[...prepared.images.map(ticket=>ticket.path),...(prepared.pdf?[prepared.pdf.path]:[])];const supabase=createClient();
   for(let index=0;index<previews.length;index+=1){setUploadStatus(`Đang tải ảnh ${index+1}/${previews.length} trực tiếp lên Supabase...`);const ticket=prepared.images[index];const{error}=await supabase.storage.from("product-assets").uploadToSignedUrl(ticket.path,ticket.token,previews[index].file,{contentType:previews[index].file.type,cacheControl:"31536000"});if(error){await discardProductUploads(saved.productId,allPaths);setState({error:"Dữ liệu sản phẩm đã lưu nhưng tải ảnh thất bại. Bạn có thể thử tải lại."});return}}
   if(pdf&&prepared.pdf){setUploadStatus("Đang tải PDF trực tiếp lên Supabase...");const{error}=await supabase.storage.from("product-assets").uploadToSignedUrl(prepared.pdf.path,prepared.pdf.token,pdf,{contentType:"application/pdf",cacheControl:"31536000"});if(error){await discardProductUploads(saved.productId,allPaths);setState({error:"Dữ liệu sản phẩm đã lưu nhưng tải PDF thất bại. Bạn có thể thử tải lại."});return}}
   setUploadStatus("Đang xác minh và liên kết file...");const finalized=await finalizeProductUploads(saved.productId,{images:previews.map((item,index)=>({path:prepared.images[index].path,name:item.file.name,size:item.file.size,type:item.file.type,altText:item.altText||name})),pdf:pdf&&prepared.pdf?{path:prepared.pdf.path,name:pdf.name,size:pdf.size,type:pdf.type}:null});
   if(finalized.error){setState({error:finalized.error});return}
   setDirty(false);router.push(`/admin/san-pham/${saved.productId}?saved=1`);router.refresh();
  }catch{setState({error:"Có lỗi khi lưu sản phẩm hoặc tải file. Vui lòng thử lại."})}finally{setPending(false);setUploadStatus("")}
 }
 return <form onSubmit={handleSubmit} className="product-form" onChange={()=>setDirty(true)}>
  <input type="hidden" name="id" value={product?.id||""}/><input type="hidden" name="specs" value={JSON.stringify(specs.filter(s=>s.name||s.value))}/>
  <div className="admin-page-head form-heading"><div><Link href="/admin/san-pham" className="back-link">← Sản phẩm</Link><h1>{product?"Sửa sản phẩm":"Thêm sản phẩm"}</h1><p>Tự động tạo slug, định dạng mô tả và kiểm soát ảnh tại một nơi.</p></div><div>{product&&<><Link href={`/admin/san-pham/${product.id}/lich-su`} className="button button-secondary"><History/> Lịch sử</Link><Link href={`/admin/san-pham/${product.id}/xem-truoc`} target="_blank" className="button button-secondary"><Eye/> Xem trước</Link></>}<button type="submit" className="button button-primary" disabled={pending}><Save/> {pending?"Đang lưu...":"Lưu sản phẩm"}</button></div></div>
  {dirty&&<div className="unsaved-note">Có thay đổi chưa lưu</div>}{uploadStatus&&<div className="unsaved-note" role="status">{uploadStatus}</div>}{state.error&&<div className="form-error" role="alert">{state.error}</div>}{imageError&&<div className="form-error" role="alert">{imageError}</div>}
  <div className="form-layout"><div className="form-main">
   <section className="admin-card form-card"><h2>Thông tin cơ bản</h2><div className="field"><label htmlFor="name">Tên sản phẩm <b>*</b></label><input id="name" name="name" required maxLength={180} value={name} onChange={event=>{const value=event.target.value;setName(value);if(!slugManual)setSlug(slugifyVietnamese(value))}}/></div><div className="two-fields"><div className="field"><label htmlFor="code">Mã duy nhất <b>*</b></label><input id="code" name="code" required maxLength={60} defaultValue={product?.code}/></div><div className="field"><label htmlFor="slug">Đường dẫn (slug) <b>*</b></label><input id="slug" name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required value={slug} onChange={event=>{setSlug(slugifyVietnamese(event.target.value));setSlugManual(Boolean(event.target.value))}}/><small>Tự tạo từ tên; bạn vẫn có thể chỉnh lại.</small></div></div><div className="field"><label htmlFor="shortDescription">Mô tả ngắn</label><textarea id="shortDescription" name="shortDescription" maxLength={500} rows={3} defaultValue={product?.shortDescription}/></div><div className="field description-admin-field"><label htmlFor="description">Mô tả chi tiết</label><MarkdownEditor defaultValue={product?.description} onDirty={()=>setDirty(true)}/></div></section>
   <section className="admin-card form-card"><div className="card-head"><div><h2>Ảnh sản phẩm</h2><p>Kéo thả để đổi vị trí; nhập alt riêng cho từng ảnh.</p></div>{imagePending&&<small>Đang lưu thứ tự…</small>}</div>{existingImages.length?<div className="image-sort existing-images draggable-images">{existingImages.map(image=><div key={image.id} draggable onDragStart={()=>setDragId(image.id)} onDragOver={event=>event.preventDefault()} onDrop={()=>moveExisting(image.id)}><span className="drag-handle"><GripVertical/> Kéo ảnh</span>{image.url&&<Image src={image.url} alt={image.altText||product?.name||"Ảnh sản phẩm"} width={180} height={180} unoptimized/>}{image.isCover&&<b className="cover-badge"><Star/> Đại diện</b>}<label>Alt ảnh<input name={`imageAlt:${image.id}`} maxLength={250} value={image.altText} onChange={event=>setExistingImages(items=>items.map(item=>item.id===image.id?{...item,altText:event.target.value}:item))}/></label><div>{!image.isCover&&<button type="button" onClick={()=>coverImage(image)} title="Chọn đại diện"><Star/></button>}<button type="button" onClick={()=>removeImage(image)} title="Xóa"><Trash2/></button></div></div>)}</div>:<p className="field-help">Chưa có ảnh.</p>}
   <h2 className="subheading">Tải thêm ảnh</h2><label className="upload-zone"><ImagePlus/><strong>Nhấn để chọn tối đa 8 ảnh</strong><span>JPG, PNG hoặc WebP · tối đa 5 MB/ảnh</span><input ref={fileRef} name="images" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>choose(e.target.files)}/></label>{previews.length>0&&<div className="image-sort draggable-images">{previews.map((item,index)=><div key={item.url} draggable onDragStart={()=>setDragId(`new:${index}`)} onDragOver={event=>event.preventDefault()} onDrop={()=>{if(dragId?.startsWith("new:"))movePreview(Number(dragId.slice(4)),index)}}><span className="drag-handle"><GripVertical/> Kéo ảnh</span><Image src={item.url} alt={item.altText||`Ảnh mới ${index+1}`} width={180} height={180} unoptimized/><label>Alt ảnh<input name="newImageAlt" maxLength={250} value={item.altText} onChange={event=>sync(previews.map((preview,i)=>i===index?{...preview,altText:event.target.value}:preview))}/></label><div><button type="button" onClick={()=>{URL.revokeObjectURL(item.url);sync(previews.filter(p=>p!==item))}}><Trash2/></button></div></div>)}</div>}</section>
   <SpecificationEditor specs={specs} setSpecs={setSpecs} onDirty={()=>setDirty(true)}/>
  </div><aside className="form-side"><section className="admin-card form-card"><h2>Xuất bản</h2><div className="field"><label htmlFor="categoryId">Danh mục <b>*</b></label><select id="categoryId" name="categoryId" required defaultValue={product?.categoryId||""}><option value="" disabled>Chọn danh mục</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div><div className="field"><label htmlFor="status">Trạng thái</label><select id="status" name="status" defaultValue={product?.status||"draft"}><option value="draft">Bản nháp</option><option value="published">Xuất bản</option><option value="hidden">Ẩn</option></select></div><div className="field"><label htmlFor="price">Giá (VNĐ)</label><input id="price" name="price" type="number" min="0" step="1000" defaultValue={product?.price}/></div><label className="check-field"><input name="featured" type="checkbox" defaultChecked={product?.featured}/> Sản phẩm nổi bật</label></section><section className="admin-card form-card"><h2>Tài liệu PDF</h2>{product?.pdfPath&&<p className="field-help"><FileText/> Sản phẩm đang có tài liệu PDF.</p>}<label className="pdf-upload"><FileText/><span>{product?.pdfPath?"Chọn PDF mới để thay thế":"Chọn file PDF · tối đa 10 MB"}</span><input name="pdf" type="file" accept="application/pdf"/></label></section><div className="security-hint"><Upload/><p><strong>File được bảo vệ</strong><span>Ảnh và PDF của bản nháp chỉ quản trị viên có thể đọc.</span></p></div></aside></div>
 </form>;
}
