"use client";
import Image from "next/image";
import Link from "next/link";
import { ArrowDown,ArrowLeft,ArrowUp,FileText,ImagePlus,Save,Star,Trash2,Upload } from "lucide-react";
import { useActionState,useEffect,useRef,useState } from "react";
import { deleteProductImage, moveProductImage, saveProduct, setCoverImage } from "@/app/admin/actions/products";
import type { ActionState } from "@/app/admin/actions/types";
import type { Category,Product,ProductSpec } from "@/lib/models";

type Preview={file:File;url:string};
export function ProductEditor({product,categories}:{product?:Product;categories:Category[]}){
 const[state,action,pending]=useActionState(saveProduct,{} as ActionState);const[specs,setSpecs]=useState<ProductSpec[]>(product?.specs.length?product.specs.map(spec=>({...spec,value:spec.unit?`${spec.value} ${spec.unit}`.trim():spec.value,unit:""})):[{name:"",value:"",unit:""}]);const[previews,setPreviews]=useState<Preview[]>([]);const previewRef=useRef<Preview[]>([]);const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>()=>previewRef.current.forEach(item=>URL.revokeObjectURL(item.url)),[]);
 const sync=(next:Preview[])=>{previewRef.current=next;setPreviews(next);const transfer=new DataTransfer();next.forEach(item=>transfer.items.add(item.file));if(fileRef.current)fileRef.current.files=transfer.files};
 const choose=(files:FileList|null)=>{if(!files)return;previews.forEach(item=>URL.revokeObjectURL(item.url));sync([...files].slice(0,8).map(file=>({file,url:URL.createObjectURL(file)})))};
 return <form action={action} className="product-form"><input type="hidden" name="id" value={product?.id||""}/><input type="hidden" name="specs" value={JSON.stringify(specs.filter(s=>s.name||s.value))}/><div className="admin-page-head form-heading"><div><Link href="/admin/san-pham" className="back-link"><ArrowLeft/> Sản phẩm</Link><h1>{product?"Sửa sản phẩm":"Thêm sản phẩm"}</h1><p>Dữ liệu được kiểm tra và lưu trực tiếp vào Supabase.</p></div><div><button type="submit" className="button button-primary" disabled={pending}><Save/> {pending?"Đang lưu...":"Lưu sản phẩm"}</button></div></div>{state.error&&<div className="form-error" role="alert">{state.error}</div>}<div className="form-layout"><div className="form-main">
 <section className="admin-card form-card"><h2>Thông tin cơ bản</h2><div className="field"><label htmlFor="name">Tên sản phẩm <b>*</b></label><input id="name" name="name" required maxLength={180} defaultValue={product?.name}/></div><div className="two-fields"><div className="field"><label htmlFor="code">Mã duy nhất <b>*</b></label><input id="code" name="code" required maxLength={60} defaultValue={product?.code}/></div><div className="field"><label htmlFor="slug">Đường dẫn (slug) <b>*</b></label><input id="slug" name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required defaultValue={product?.slug}/></div></div><div className="field"><label htmlFor="shortDescription">Mô tả ngắn</label><textarea id="shortDescription" name="shortDescription" maxLength={500} rows={3} defaultValue={product?.shortDescription}/></div><div className="field description-admin-field"><label htmlFor="description">Nội dung hiển thị trong “Mô tả chi tiết”</label><textarea id="description" name="description" rows={12} placeholder={'Nhập nội dung sản phẩm tại đây.\n\nNhấn Enter để tách thành từng đoạn dễ đọc.'} defaultValue={product?.description}/><small>Mỗi lần xuống dòng sẽ tạo một đoạn riêng trên website. Chỉ nhập thông tin kỹ thuật và chứng nhận đã được xác thực.</small></div></section>
 <section className="admin-card form-card"><h2>Ảnh hiện tại</h2>{product?.images.length?<div className="image-sort existing-images">{product.images.map((image,index)=><div key={image.id}>{image.url&&<Image src={image.url} alt={image.altText||product.name} width={180} height={180} unoptimized/>}{image.isCover&&<span><Star/> Ảnh đại diện</span>}<div><button formAction={moveProductImage.bind(null,image.id)} name="direction" value="up" disabled={index===0} title="Đưa lên"><ArrowUp/></button><button formAction={moveProductImage.bind(null,image.id)} name="direction" value="down" disabled={index===product.images.length-1} title="Đưa xuống"><ArrowDown/></button>{!image.isCover&&<button formAction={setCoverImage.bind(null,image.id)} title="Chọn đại diện"><Star/></button>}<button formAction={deleteProductImage.bind(null,image.id)} title="Xóa"><Trash2/></button></div></div>)}</div>:<p className="field-help">Chưa có ảnh.</p>}<h2 className="subheading">Tải thêm ảnh</h2><label className="upload-zone"><ImagePlus/><strong>Nhấn để chọn tối đa 8 ảnh</strong><span>JPG, PNG hoặc WebP · tối đa 5 MB/ảnh</span><input ref={fileRef} name="images" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>choose(e.target.files)}/></label>{previews.length>0&&<div className="image-sort">{previews.map((item,index)=><div key={item.url}><Image src={item.url} alt={`Ảnh mới ${index+1}`} width={180} height={180} unoptimized/>{index===0&&<span><Star/> Đại diện nếu chưa có</span>}<div><button type="button" disabled={index===0} onClick={()=>{const n=[...previews];[n[index-1],n[index]]=[n[index],n[index-1]];sync(n)}}><ArrowUp/></button><button type="button" disabled={index===previews.length-1} onClick={()=>{const n=[...previews];[n[index+1],n[index]]=[n[index],n[index+1]];sync(n)}}><ArrowDown/></button><button type="button" onClick={()=>{URL.revokeObjectURL(item.url);sync(previews.filter(p=>p!==item))}}><Trash2/></button></div></div>)}</div>}</section>
 <section className="admin-card form-card"><div className="card-head"><div><h2>Thông số kỹ thuật</h2><p>Nhập tên thông số và toàn bộ nội dung cần hiển thị trong phần chi tiết.</p></div><button type="button" className="button button-secondary" onClick={()=>setSpecs([...specs,{name:"",value:"",unit:""}])}>+ Thêm dòng</button></div><div className="spec-editor legacy-spec-editor">{specs.map((spec,index)=><div key={spec.id||index}><input aria-label="Tên thông số" placeholder="Tên thông số" value={spec.name} onChange={e=>setSpecs(specs.map((s,i)=>i===index?{...s,name:e.target.value}:s))}/><input aria-label="Chi tiết" placeholder="Chi tiết" value={spec.value} onChange={e=>setSpecs(specs.map((s,i)=>i===index?{...s,value:e.target.value,unit:""}:s))}/><button type="button" onClick={()=>setSpecs(specs.filter((_,i)=>i!==index))}><Trash2/></button></div>)}</div></section></div>
 <aside className="form-side"><section className="admin-card form-card"><h2>Xuất bản</h2><div className="field"><label htmlFor="categoryId">Danh mục <b>*</b></label><select id="categoryId" name="categoryId" required defaultValue={product?.categoryId||""}><option value="" disabled>Chọn danh mục</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div><div className="field"><label htmlFor="status">Trạng thái</label><select id="status" name="status" defaultValue={product?.status||"draft"}><option value="draft">Bản nháp</option><option value="published">Xuất bản</option><option value="hidden">Ẩn</option></select></div><div className="field"><label htmlFor="price">Giá (VNĐ)</label><input id="price" name="price" type="number" min="0" step="1000" defaultValue={product?.price}/></div><label className="check-field"><input name="featured" type="checkbox" defaultChecked={product?.featured}/> Sản phẩm nổi bật</label></section><section className="admin-card form-card"><h2>Tài liệu PDF</h2>{product?.pdfPath&&<p className="field-help"><FileText/> Sản phẩm đang có tài liệu PDF.</p>}<label className="pdf-upload"><FileText/><span>{product?.pdfPath?"Chọn PDF mới để thay thế":"Chọn file PDF · tối đa 10 MB"}</span><input name="pdf" type="file" accept="application/pdf"/></label></section><div className="security-hint"><Upload/><p><strong>File được bảo vệ</strong><span>Ảnh và PDF nằm trong bucket riêng tư; quyền đọc phụ thuộc trạng thái sản phẩm.</span></p></div></aside></div></form>
}
